#!/bin/bash

# Adapted from default '.git/hooks/pre-commit.sample'.
if git rev-parse --verify HEAD >/dev/null 2>&1
then
    against=HEAD
fi

# Redirect output to stderr.
exec 1>&2

# Avoid non-ASCII filenames
# We exploit the fact that the printable range starts
# at the space character and ends with tilde.
if test $(git diff --cached --name-only --diff-filter=A -z $against |
          LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
    cat <<\EOF
Error: Attempt to add a non-ASCII file name.
EOF
    exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
