---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^vscode/settings\.json$|
            ^vscode/extensions\.json$
          )
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/Vimjas/vint
    rev: db881f8fe7127cd092436371643e48903099f114 # frozen: v0.4a3
    hooks:
      - id: vint
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/codespell-project/codespell
    rev: 57b21406f092110c18776e39b0bda50d37c945c8 # frozen: v2.4.3
    hooks:
      - id: codespell
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/google/yamlfmt
    rev: b5ca1890231d5e1e5181fef75a1be609d1e25029 # frozen: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: a6564f5d57444e123433a5c9af733e3975c77229 # frozen: v0.11.0.1-1
    hooks:
      - id: shellcheck
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 0c19a2b41e5514bc74f36c3eed4de554f989b666 # frozen: v4.19.1
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual, pre-push]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8 # frozen: v1.5.6
    hooks:
      - id: remove-tabs
        exclude: |
          (?x)(
            ^.git/COMMIT_EDITMSG$
          )
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: e8b4e28241a9ae8296ba6e4a491b5da4eda73283 # frozen: 3.11.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: 479be5958357ba5ab65ce47172117348516860e9 # frozen: v3.14.1-1
    hooks:
      - id: shfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 4f85d46a92dc17713078e5de73f8a13190edf6fc # frozen: 0.38.2
    hooks:
      - id: check-github-workflows
      - id: check-renovate

ci:
  autoupdate_schedule: quarterly
  autofix_prs: false
