---
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: |
          (?x)(
            ^vscode/settings\.json$|
            ^vscode/extensions\.json$
          )
      - id: check-added-large-files
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: detect-private-key
  - repo: https://github.com/Vimjas/vint
    rev: db881f8fe7127cd092436371643e48903099f114 # frozen: v0.4a3
    hooks:
      - id: vint
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/codespell-project/codespell
    rev: 2ccb47ff45ad361a21071a7eedda4c37e6ae8c5a  # frozen: v2.4.2
    hooks:
      - id: codespell
        exclude: |
          (?x)(
            ^vim/autoload/plug\.vim$
          )
  - repo: https://github.com/google/yamlfmt
    rev: b5ca1890231d5e1e5181fef75a1be609d1e25029  # frozen: v0.21.0
    hooks:
      - id: yamlfmt
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: 745eface02aef23e168a8afb6b5737818efbea95 # frozen: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 4fbeae7861663ecf4b4989211eba41c1a3fb1227  # frozen: v4.13.9
    hooks:
      - id: commitizen
      - id: commitizen-branch
        stages: [manual, pre-push]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: ad1b27d73581aa16cca06fc4a0761fc563ffe8e8  # frozen: v1.5.6
    hooks:
      - id: remove-tabs
        exclude: |
          (?x)(
            ^.git/COMMIT_EDITMSG$
          )
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: bebfac867564fbd992e5b45379b4b0568d5cb85b  # frozen: 3.6.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: e26a818fd47b4f33cefa99035d1265b0849f4b47  # frozen: v3.13.0-1
    hooks:
      - id: shfmt
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: ed81924a8b1cecdaa570b072528fa80c9c4d6ccd  # frozen: 0.37.1
    hooks:
      - id: check-github-workflows
      - id: check-renovate

ci:
  autoupdate_schedule: quarterly
  autofix_prs: false
