[lint]
select = ["ALL"]
preview = true
ignore = [
    "ANN202",
    "ANN204",
    "COM812",
    "CPY001",
    "D102",
    "D103",
    "D104",
    "D105",
    "D203",
    "D211",
    "D213",
    "E501",
    "EM101",
    "EM102",
    "FIX001",
    "PLR2004",
    "PLW2901",
    "PTH123",
    "RET504",
    "T201",
    "TD001",
    "TD003",
    "TRY003",
]

[lint.per-file-ignores]
"test_*.py" = [
    "ANN001",
    "ANN201",
    "D100",
    "D101",
    "D107",
    "EM101",
    "INP001",
    "PLC1901",
    "S101",
    "S404",
    "S603",
    "SLF001",
    "T201",
]
