[lint]
select = ["ALL"]
preview = true
ignore = [
    "ANN202",
    "COM812",
    "CPY001",
    "E501",
    "D103",
    "D211",
    "D213",
    "FIX001",
    "PLR2004",
    "PLW2901",
    "TD001",
    "TD003",
]

[per-file-ignores]
"test_*.py" = [
    "ANN001", "ANN201", "D100", "INP001", "S101", "S404", "S603", "T201"
]
