#!/bin/sh
################################### My aliases #################################

###miscellaneous aliases
alias ll='ls -l'
alias la='ls -al'
alias l='ls -F1'
alias cl='reset'
alias kfi='pkill -f /usr/lib/firefox/firefox && (firefox &> /dev/null &)'
alias pingTest='ping 8.8.8.8'
alias testHDMI='speaker-test -c 2 -r 48000 -D hw:0,3'
alias grep='grep --color=auto --exclude-dir={.git,.svn,.hg}'
alias cgrep='grep --color=always --exclude-dir={.git,.svn,.hg}'
# to run make in the background
alias backmake='make &> /dev/null &'

###for cd into ancestor directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

###shortcuts for programs
alias py='python3'
alias vi='vim'
alias vless='vim -R -'

###shortcuts for svn
alias sst='svn status'
alias sa='svn add'
alias su='svn update'
alias sci='svn commit'
alias sinf='svn info'
alias sd='svn diff'
alias svnignore='svn propset svn:ignore -RF ./.svnignore .'

###shortcuts for mercurial
alias hglg='hg log --stat'
alias hga='hg add'

### shortcuts for git commands
# to activate colors in terminal via ssh
alias gd='git diff --color'


################################ My alias functions ############################

#alias function for parallel make
function pmake() {
    ncpu=$(nproc)
    upper_limit=10
    if (( ncpu > 10 ));
    then
        ncpu=$upper_limit
    fi;
    make -j$ncpu "$@";
}

#alias function for colordiff for svn
function sdc() {
    svn diff $1 | colordiff | less -R
}

#opens a file the standard way and leads the output to null
function op {
    xdg-open $1 > /dev/null
    sleep 0.35
    :
}

#function to wait for a valid answer from the user in a loop
function confirmLoop() {
    varConfirm=$(confirm);
    compare=2;
    while true;
    do
        if ((varConfirm == compare));
        then
            varConfirm=$(confirm);
        else
            break;
        fi;
    done;
    echo $varConfirm;
}

#function to let the user confirm his previos decision
function confirm () {
    read -p "" choice;
    if [ "$choice" == "Y" ];
    then
        echo 0;
    elif [ "$choice" == "n" ];
    then
        echo 1;
    else
        echo 2;
    fi;
}

#a function to create a directory and directly move into it
function mkcd {
  if [ ! -n "$1" ]; then
    echo "Enter a directory name"
  elif [ -d $1 ]; then
    echo "\`$1' already exists"
  else
    mkdir $1 && cd $1
  fi
}

function md2html {
    markdownfile=$1
    htmlfile=${markdownfile%".md"}".html"
    markdown $markdownfile > $htmlfile
}

function cless {
    pygmentize -f terminal "$1" | less -R
}
