#!/bin/sh
###This file contains all the settings shared between different shells(bash, zsh)
###It just sources(enables) the other shared files, if they exist

#to include the shared aliases, if they exist
if [ -f $HOME/.shared_aliases ]; then
	source $HOME/.shared_aliases
fi

#to include the shared environemt variables, if they exist
if [ -f $HOME/.env ]; then
	source $HOME/.env
fi

# Put any proprietary or private functions/values in ~/.private, and this will source them
if [ -f $HOME/.private ]; then
	source $HOME/.private
fi

eval `dircolors ~/.dircolors-solarized/dircolors.ansi-dark`
