#!/bin/sh  

export PYTHONPATH="$HOME/.local/lib/python2.7/site-packages:$HOME/.local/lib/python3.4/site-packages/"

#to include the shared aliases, if they exist
if [ -f $HOME/.shared_aliases ]; then
	source $HOME/.shared_aliases
fi

#set vim as standard editor, also for visual
export VISUAL=vim
export EDITOR="$VISUAL"

# Put any proprietary or private functions/values in ~/.private, and this will source them
if [ -f $HOME/.private ]; then
	source $HOME/.private
fi
